name: authentication_repository
description: Dart package which manages authentication domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  cloud_firestore: ^3.3.0
  equatable: ^2.0.3
  firebase_auth: ^3.4.2
  flutter:
    sdk: flutter
